version: '3.9'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    networks:
      - dbnet
    volumes:
      - type: bind
        source: ${LOCAL_DB_DIR}
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}

  backend:
    container_name: mangawatcher-backend
    image: tacticalminky/mangawatcher-backend
    build: ./server
    ports:
      - 8091:8091
    networks:
      - dbnet
      - apinet
    environment:
      MONGODB_URI: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongo:27017
      MONGODB_DB: ${MONGODB_DB}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    depends_on:
      - mongo
  
  frontend:
    container_name: mangawatcher-frontend
    image: tacticalminky/mangawatcher-frontend
    build: ./client
    ports:
      - 4200:80
    networks:
      - apinet
      # - proxynet
    depends_on:
      - backend

networks:
  dbnet:
    driver: bridge
  apinet:
    driver: bridge
  # proxynet:
  #   name: proxynet
  #   external: true
