services:
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - dbnet
    volumes:
      - type: bind
        source: ${APPDATA_PATH:-.}/db
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-mangawatcher}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGODB_DB:-mangawatcher}

  mangawatcher:
    container_name: mangawatcher
    image: tacticalminky/mangawatcher
    build: .
    ports:
      - 8091:8091
    networks:
      - dbnet
      # - proxynet
    environment:
      MONGODB_URI: mongodb://${MONGODB_USER:-mangawatcher}:${MONGODB_PASSWORD:-password}@mongo:27017
        #MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: ${MONGODB_DB:-mangawatcher}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    depends_on:
      - mongo

networks:
  dbnet:
    driver: bridge
  # proxynet:
  #   name: proxynet
  #   external: true
